### ISSUE TITLE
 heartbeat_interval is not being honored by poll query type

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#106]
Problem Description/Summary :
--------------------------------------------
 heartbeat_interval is not being honored by poll query type

Expected Behavior : 
------------------------
Poll response should be sent out after heart beat interval expiry

Topology :
------------
DUT

Steps to Repro :
--------------------
1. Initiate a poll query for every 30s with a heartbeat_interval of 20s.

 

root@sonic:/home/admin# docker exec -it telemetry bash -c  "./gnmi_cli -insecure -logtostderr -address 127.0.0.1:8080 -query_type p -pi 30s -heartbeat_interval 20 -q /openconfig-interfaces:interfaces/ -v 0 -target OC-YANG"

2. Observe that poll response is not being sent after heartbeat_interval expiry. It is only sent after every 30s.

Sep 11 06:35:19.194013 sonic INFO telemetry#supervisord: telemetry I0911 06:35:19.193492 38 translib.go:385] Received Get request for path = /openconfig-system:system

(truncated)......

 

Sep 11 06:35:49.408365 sonic INFO telemetry#supervisord: telemetry I0911 06:35:49.404652 38 translib.go:385] Received Get request for path = /openconfig-system:system

Primary Analysis by DevTest (Level of debugging done / Devtest Observation ) :
---------------------------------------------------------------------------------------------------------
Heartbeat interval is being ignored

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------

 3/3

**Comment by sachin-brm** [comment]
[poll_heart_beat.txt](https://github.com/project-arlo/sonic-mgmt-framework/files/3600502/poll_heart_beat.txt)

**Comment by jeffyin-dell** [comment]
@sachin-brm heartbeat_interval is in nanoseconds according to @seiferteric . Please try with a parameter of 20000000000 instead of 20. 
Closing this bug for now, but please feel free to reopen if there's still an issue.

**Comment by PrabhuSreenivasan** [comment]
We tested the same with modified gnmi_cli tool which takes and configures the heartbeat_interval in seconds. We notice that the value of heartbeat_interval does not have any effect on the behavior on polling mode. It works only on streaming mode.

**Comment by seiferteric** [comment]
Oh yes that is true, heartbeat is only relevant for streaming mode https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#35152-stream-subscriptions

**Comment by jeffyin-dell** [comment]
So is this a bug? Should the gnmi_cli tool be modified to reject heartbeat_interval in polling mode?

**Comment by seiferteric** [comment]
here is a fix anyway: https://github.com/project-arlo/sonic-telemetry/pull/31
