### ISSUE TITLE
DELLCLI: Sonic - SONIC_2.0 - SONIC 2.0: "show interface status" command displaying with the suffix "GB" instead of "G" when executed from sonic-cli

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#142]
Problem Description/Summary :
--------------------------------------------
Speed of the interface displaying with the suffix "GB" instead of "G"

Expected Behavior : 
------------------------
Speed should display with the suffix "G"

Topology :
------------
DUT

Steps to Repro :
--------------------
1) Go to sonic-cli and execute the command "show interface status"

2) Observing that speed of the output displaying with the suffix "GB"

 

 

Ethernet68 - up up 10GB 9100
Ethernet69 - up up 10GB 9100

Are logs(Syslog/Scriptlogs/Console logs / core dump file like – /var/dump/sonic_dump_sonic_20190709_120423.tar.gz) attached ? :
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Yes

Primary Analysis by DevTest (Level of debugging done / Devtest Observation ) :
---------------------------------------------------------------------------------------------------------
No

Has a developer been contacted?? If so, what is the result of the investigation? : 
------------------------------------------------------------------------------------------------------
[show_interface_status.log](https://github.com/project-arlo/sonic-mgmt-framework/files/3674557/show_interface_status.log)
No

Is show tech support data attached? : 
--------------------------------------------------
Yes

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------

 Everytime

**Comment by justinejose91** [comment]
Yes, will address this issue soon.

**Comment by sachin-brm** [comment]
Thanks Justine. Can you please provide the fix in next couple of days? We have this issue targeted for Arlo+ and need to have this fixed by Wednesday (10/9).

**Comment by jeffyin-dell** [comment]
@justinejose91 is this fixed? @sachin-brm gave a deadline of today.

**Comment by justinejose91** [comment]
I will do it by end of today.

**Comment by justinejose91** [comment]
Done and merged yesterday. Closing this one.
