### ISSUE TITLE
Giving Interface name and trunk-vlan instance in the Python Script as Keypath throws error for deletion of trunk-vlan

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#149]
Following is the error.
File "/usr/sbin/cli/sonic-cli-if.py", line 186, in run
    api_response = getattr(aa,func.__name__)(*keypath)
TypeError: delete_openconfig_vlan_interfaces_interface_ethernet_switched_vlan_config_trunk_vlans() takes exactly 2 arguments (3 given)

Do I need to pass trunk-vlan instance as part of key or body? I guess, we need to make some changes in the openapi script for this support.

**Comment by justinejose91** [comment]
@sachinholla Could you please assign it to the right person?

**Comment by faraazbrcm** [comment]
@justinejose91 looks like you are not trying the right API. The API you are trying to use is to delete all instance of leaf-list

You should use below one if you intend to delete one instance of leaf-list

The REST URI for the below API is (The same can also be seen from Swagger UI (operationID) against the below URI.

/restconf/data/openconfig-interfaces:interfaces/interface={name}/openconfig-if-aggregate:aggregation/openconfig-vlan:switched-vlan/config/trunk-vlans={trunk-vlans}

```
def del_llist_openconfig_vlan_interfaces_interface_ethernet_switched_vlan_config_trunk_vlans(self, name, trunk_vlans, **kwargs):  # noqa: E501
        """del_llist_openconfig_vlan_interfaces_interface_ethernet_switched_vlan_config_trunk_vlans  # noqa: E501

        OperationId: del_llist_openconfig_vlan_interfaces_interface_ethernet_switched_vlan_config_trunk_vlans 
```
