### ISSUE TITLE
Admin-status configuration for VLAN is not getting reflected in the APP-DB

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#163]
admin_status is getting reflected in the CONFIG-DB, but not in APP-DB. Do we have this support?

**Comment by sachinholla** [comment]
Hi @justinejose91, I will check check with relevant teams and get back.. Can you provide the config-db dump for the vlan entry?

**Comment by sachinholla** [comment]
@justinejose91, as per SONiC wiki https://github.com/Azure/SONiC/wiki/Configuration#vlan we don't have admin_status support in VLAN table. Not sure if it was added later..

**Comment by sachinholla** [comment]
App team confirmed that vlan admin status config is not supported. We dont have corresponding click commands as well.
