### ISSUE TITLE
BGP configuration using OC network instance is not working

### ISSUE THREAD

**Issue by venkatmahalingam** [project-arlo/sonic-mgmt-framework#177]
Looks like we still have an issue (mapping keys – highlighted below) even with the latest project-arlo, please take a look at the below for debugging.

Please use “frr-bgp-nbi-support” (project-arlo) branch for any sanity REST operations.

$ curl -k -X PATCH "https://10.11.47.38/restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,bgp/bgp/global/config/as" -H "accept: application/yang-data+json" -H "Content-Type: application/yang-data+json" -d "{ \"openconfig-network-instance:as\": 100}"

{"ietf-restconf:errors":{"error":[{"error-type":"protocol","error-tag":"invalid-value","error-message":"error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path \"/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as\": trailing garbage following keys in element protocol, got: {name}"}]}}
$

curl -k -X GET "https://10.11.47.38/restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,bgp/bgp/global/config/as" -H "accept: application/yang-data+json" -H "Content-Type: application/yang-data+json"
{"ietf-restconf:errors":{"error":[{"error-type":"protocol","error-tag":"invalid-value","error-message":"error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path \"/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as\": trailing garbage following keys in element protocol, got: {name}"}]}}vmahalingam@xenlogin-eqx-08:~$
vmahalingam@xenlogin-eqx-08:~$

Oct 14 23:13:12.839248 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.837994      17 router.go:122] [REST-20] Recevied PatchOpenconfigNetworkInstanceNetworkInstancesNetworkInstanceProtocolsProtocolBgpGlobalConfigAs request from 10.14.8.138:33078
Oct 14 23:13:12.839248 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838094      17 handler.go:47] [REST-20] PATCH /restconf/data/openconfig-network-instance:network-instances/network-instance=default/protocols/protocol=BGP,bgp/bgp/global/config/as; content-len=40
Oct 14 23:13:12.839248 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838179      17 handler.go:134] [REST-20] Content-type=application/yang-data+json; data={ "openconfig-network-instance:as": 100}
Oct 14 23:13:12.839248 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838227      17 handler.go:55] [REST-20] Translated path = /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as
Oct 14 23:13:12.839248 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838249      17 translib.go:203] Update request received with path =/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as
Oct 14 23:13:12.839298 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838268      17 translib.go:204] Update request received with payload ={ "openconfig-network-instance:as": 100}
Oct 14 23:13:12.839298 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838287      17 app_interface.go:130] getAppModule called for path =/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as
Oct 14 23:13:12.839337 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838308      17 app_interface.go:143] No app module registered for path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as hence fallback to default/common app
Oct 14 23:13:12.839337 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838334      17 app_interface.go:165] cast to appInterface worked&{<nil> <nil> <nil> map[] []}
Oct 14 23:13:12.839337 sonic INFO mgmt-framework#supervisord: rest-server E1014 23:13:12.838491      17 request_binder.go:230] Error in uri to path conversion: error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path "/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as": trailing garbage following keys in element protocol, got: {name}
Oct 14 23:13:12.839365 sonic INFO mgmt-framework#supervisord: rest-server E1014 23:13:12.838519      17 request_binder.go:125] Error in creating the target object : error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path "/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as": trailing garbage following keys in element protocol, got: {name}
Oct 14 23:13:12.839365 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838560      17 translib.go:794] Error in request binding: error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path "/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as": trailing garbage following keys in element protocol, got: {name}
Oct 14 23:13:12.839389 sonic INFO mgmt-framework#supervisord: rest-server E1014 23:13:12.838608      17 handler.go:59] [REST-20] Translib error tlerr.TranslibSyntaxValidationError - error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path "/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as": trailing garbage following keys in element protocol, got: {name}
Oct 14 23:13:12.839434 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838680      17 handler.go:72] [REST-20] Sending response 400, type=application/yang-data+json, data={"ietf-restconf:errors":{"error":[{"error-type":"protocol","error-tag":"invalid-value","error-message":"error building structured path: error parsing path /openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as: trailing garbage following keys in element protocol, got: {name}, error building string slice path: error parsing path \"/openconfig-network-instance:network-instances/network-instance[name=bgp]/protocols/protocol[identifier=BGP]{name}/bgp/global/config/as\": trailing garbage following keys in element protocol, got: {name}"}]}}
Oct 14 23:13:12.839481 sonic INFO mgmt-framework#supervisord: rest-server I1014 23:13:12.838733      17 router.go:128] [REST-20] PatchOpenconfigNetworkInstanceNetworkInstancesNetworkInstanceProtocolsProtocolBgpGlobalConfigAs took 681.681µs

**Comment by sachinholla** [comment]
Swagger does not handle the paths with duplicate key names. Key "name" is repeated in the above path. Working on a fix to modify the key name to a unique name in swagger layer only. REST Server will have to map this modified key name to yang defined name.

**Comment by mbalachandar** [comment]
@venkatmahalingam Could you please close this issue, if it is fixed

**Comment by venkatmahalingam** [comment]
Yes, this issue has been fixed.
