### ISSUE TITLE
PortChannel IP configuration not getting reflected on Linux kernel

### ISSUE THREAD

**Issue by Tejaswi-Goel** [project-arlo/sonic-mgmt-framework#183]
Entry in ConfigDB : 
```
127.0.0.1:6379[4]> hgetall "PORTCHANNEL_INTERFACE|PortChannel11|11.1.1.1/24"
1) "NULL"
2) "NULL"
```
```
root@sonic:~# ifconfig PortChannel11
PortChannel11: flags=4099<UP,BROADCAST,MULTICAST>  mtu 9000
        ether 4c:76:25:e5:37:40  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by justinejose91** [comment]
Please create an entry with PORTCHANNEL_INTERFACE|PortChannel11 before creating the entry PORTCHANNEL_INTERFACE|PortChannel11|11.1.1.1/24? Could you check that?

**Comment by joyas-joseph** [comment]
Could someone explain the requirement for this entry to be present in the DB?

**Comment by Tejaswi-Goel** [comment]
> PORTCHANNEL_INTERFACE|PortChannel11

Currently, adding just the entry - "PORTCHANNEL_INTERFACE|PortChannel11" is not supported by sonic-portchannel-interface.yang , I can modify the sonic-portchannel-interface.yang and try again.

**Comment by Tejaswi-Goel** [comment]
> Could someone explain the requirement for this entry to be present in the DB?

The PORTCHANNEL_INTERFACE Table requires objects to have the interface as first-level key, and IP prefix as second-level key. And `intfsmgrd` is responsible for port/port channel/VLAN IP configuraton changes. Related tables: `PORT_INTERFACE`, `VLAN_INTERFACE`.

**Comment by Tejaswi-Goel** [comment]
After adding new list in sonic-portchannel-interface.yang to support entry with only  first-level key --> "PORTCHANNEL_INTERFACE|PortChannel11" , the IP config is getting reflected on Linux Kernel . Thank you @justinejose91 .

**Comment by joyas-joseph** [comment]
I am trying to understand why "PORTCHANNEL_INTERFACE|PortChannel" needs to exist when "PORTCHANNEL_INTERFACE|PortChannel11|11.1.1.1/24" has all the required information to assign the IP address. What dependency exists in intfmgrd?

**Comment by sachinholla** [comment]
As per SONiC design "PORTCHANNEL_INTERFACE|PortChannel11" key indicates that po11 is a L3 interface. Its value includes L3 properties like vrf binding. Key "PORTCHANNEL_INTERFACE|PortChannel11|11.1.1.1/24" indicates only IP address. Without 1st entry the port is not considered an L3 interface.

**Comment by joyas-joseph** [comment]
Thanks for the info.

Where can I find the schema information for this entry?

**Comment by sachinholla** [comment]
VRF design spec... Key with only interface name was introduced for vrf support and that entry is a must before adding any ip address. Details are at https://github.com/Azure/SONiC/blob/master/doc/vrf/sonic-vrf-hld.md#add-vrf-binding-information-in-config_dbjson-file .
