### ISSUE TITLE
Transformer create does not create the top level instance list in PTP

### ISSUE THREAD

**Issue by anand-kumar-subramanian** [project-arlo/sonic-mgmt-framework#203]
PTP_INSTANCE table is not getting created through transformer. The yang, annotation and xformer files can be found in the issue https://github.com/project-arlo/sonic-mgmt-framework/issues/189

       CREATE Request uri - "/ietf-ptp:ptp"
     json paylod is as follows : (NOTE : Since translib - request_binder.go was throwing error and not allowing to reach app/transformer , 
                                  have excluded, from paylod ,the binary data-type field values clock-identity and grandmaster-identity.
     
     I1025 17:07:53.044883   44185 translib.go:136] Create request received with payload ={
    "ietf-ptp:instance-list": [{
        "instance-number": 0,
        "default-ds": {
            "two-step-flag": true,
            "number-ports": 0,
            "clock-quality": {
                "clock-class": 0,
                "clock-accuracy": 0,
                "offset-scaled-log-variance": 0
            },
            "priority1": 0,
            "priority2": 0,
            "domain-number": 0,
            "slave-only": true
        },
        "current-ds": {
            "steps-removed": 0,
            "offset-from-master": "0",
            "mean-path-delay": "0"
        },
        "parent-ds": {
            "parent-port-identity": {
                "port-number": 0
            },
            "parent-stats": true,
            "observed-parent-offset-scaled-log-variance": 0,
            "observed-parent-clock-phase-change-rate": 0,
            "grandmaster-clock-quality": {
                "clock-class": 0,
                "clock-accuracy": 0,
                "offset-scaled-log-variance": 0
            },
            "grandmaster-priority1": 0,
            "grandmaster-priority2": 0
        },
        "time-properties-ds": {
            "current-utc-offset-valid": true,
            "current-utc-offset": 0,
            "leap59": true,
            "leap61": true,
            "time-traceable": true,
            "frequency-traceable": true,
            "ptp-timescale": true,
            "time-source": 0
        },
        "port-ds-list": [{
            "port-number": 0,
            "port-state": "initializing",
            "underlying-interface": "string",
            "log-min-delay-req-interval": 0,
            "peer-mean-path-delay": "0",
            "log-announce-interval": 0,
            "announce-receipt-timeout": 0,
            "log-sync-interval": 0,
            "delay-mechanism": "e2e",
            "log-min-pdelay-req-interval": 0,
            "version-number": 0
        }]
    }],
    "ietf-ptp:transparent-clock-default-ds": {
        "number-ports": 0,
        "delay-mechanism": "e2e",
        "primary-domain": 0
    },
    "ietf-ptp:transparent-clock-port-ds-list": [{
        "port-number": 0,
        "log-min-pdelay-req-interval": 0,
        "faulty-flag": true,
        "peer-mean-path-delay": "0"
    }]
}
Redis Data created by transformer :  The format is map[table-name]map[table-key]map[field-name]field-value 
I1025 17:07:53.847484   44185 common_app.go:282] transformer.XlateToDb() returnedmap[PTP_CLOCK:map[GLOBAL:{map[clock_accuracy:0 clock_class:248 domain_number:0 number_ports:0 offset_scaled_log_variance:0 priority1:0 priority2:0 slave_only:true tc_delay_mechanism:e2e tc_number_ports:0 tc_primary_domain:0 two_step_flag:true]}] PTP_CURRENTDS:map[GLOBAL:{map[mean_path_delay:0 offset_from_master:0 steps_removed:0]}] PTP_PARENTDS:map[GLOBAL:{map[clock_accuracy:0 clock_class:248 grandmaster_priority1:0 grandmaster_priority2:0 observed_parent_clock_phase_change_rate:0 observed_parent_offset_scaled_log_variance:65535 offset_scaled_log_variance:0 parent_stats:false port_number:0]}] PTP_PORT:map[Ethernet0:{map[announce_receipt_timeout:0 delay_mechanism:e2e log_announce_interval:0 log_min_delay_req_interval:0 log_min_pdelay_req_interval:0 log_sync_interval:0 peer_mean_path_delay:0 port_state:initializing underlying_interface:string version_number:0]}] PTP_TC_PORT:map[Ethernet0:{map[faulty_flag:false log_min_pdelay_req_interval:0 peer_mean_path_delay:0]}] PTP_TIMEPROPDS:map[GLOBAL:{map[current_utc_offset:0 current_utc_offset_valid:true frequency_traceable:true leap59:true leap61:true ptp_timescale:true ptp_timesource:0 time_traceable:true]}]]
Above log indented for better understanging :
[PTP_CLOCK:
           map[GLOBAL:
                  {map[clock_accuracy:0 
                       clock_class:248 
                       domain_number:0 
                       number_ports:0 
                       offset_scaled_log_variance:0 
                       priority1:0 
                       priority2:0 
                       slave_only:true 
                       tc_delay_mechanism:e2e 
                       tc_number_ports:0 
                       tc_primary_domain:0 
                       two_step_flag:true]}
           ]
PTP_CURRENTDS:
           map[GLOBAL:
                 {map[mean_path_delay:0 
                      offset_from_master:0 
                      steps_removed:0]}
           ] 
PTP_PARENTDS:
           map[GLOBAL:
                 {map[clock_accuracy:0 
                      clock_class:248 
                      grandmaster_priority1:0 
                      grandmaster_priority2:0 
                      observed_parent_clock_phase_change_rate:0 
                      observed_parent_offset_scaled_log_variance:65535 
                      offset_scaled_log_variance:0 parent_stats:false port_number:0]}
           ] 
PTP_PORT:
         map[Ethernet0:
                {map[announce_receipt_timeout:0 
                     delay_mechanism:e2e 
                     log_announce_interval:0 
                     log_min_delay_req_interval:0 
                     log_min_pdelay_req_interval:0 
                     log_sync_interval:0 peer_mean_path_delay:0 
                     port_state:initializing underlying_interface:string version_number:0]}
         ] 
PTP_TC_PORT:
        map[Ethernet0:
              {map[faulty_flag:false 
                   log_min_pdelay_req_interval:0 
                   peer_mean_path_delay:0]}
        ] 
PTP_TIMEPROPDS:
        map[GLOBAL:
              {map[current_utc_offset:0 
                   current_utc_offset_valid:true 
                   frequency_traceable:true 
                   leap59:true 
                   leap61:true 
                   ptp_timescale:true 
                   ptp_timesource:0 time_traceable:true]}
         ]
]

**Comment by amrutasali** [comment]
We have added  fix to transfomer-phase2 branch.The result map created by transformer now contains the PTP_INSTANCE table.

Note : At ptp/instance-list the annoation is table-name, the key transformer can be removed.

deviation /ptp:ptp/ptp:instance-list {
        deviate add {
               + sonic-ext:table-name "PTP_INSTANCE";
               - sonic-ext:key-transformer "ptpinstance_key_xfmr";
        }
}

The result map/tranlsation from transformer :
 I1028 23:39:17.657943   40029 common_app.go:320] Processing DB operation for map[PTP_CLOCK:map[GLOBAL:{map[clock_accuracy:0 clock_class:248 domain_number:0 number_ports:0 offset_scaled_log_variance:0 priority1:0 priority2:0 slave_only:true tc_delay_mechanism:e2e tc_number_ports:0 tc_primary_domain:0 two_step_flag:true]}] PTP_CURRENTDS:map[GLOBAL:{map[mean_path_delay:0 offset_from_master:0 steps_removed:0]}] PTP_INSTANCE:map[0:{map[NULL:NULL]}] PTP_PARENTDS:map[GLOBAL:{map[clock_accuracy:0 clock_class:248 grandmaster_priority1:0 grandmaster_priority2:0 observed_parent_clock_phase_change_rate:0 observed_parent_offset_scaled_log_variance:65535 offset_scaled_log_variance:0 parent_stats:false port_number:0]}] PTP_PORT:map[Ethernet0:{map[announce_receipt_timeout:0 delay_mechanism:e2e log_announce_interval:0 log_min_delay_req_interval:0 log_min_pdelay_req_interval:0 log_sync_interval:0 peer_mean_path_delay:0 port_state:initializing underlying_interface:string version_number:0]}] PTP_TC_PORT:map[Ethernet0:{map[faulty_flag:false log_min_pdelay_req_interval:0 peer_mean_path_delay:0]}] PTP_TIMEPROPDS:map[GLOBAL:{map[current_utc_offset:0 current_utc_offset_valid:true frequency_traceable:true leap59:true leap61:true ptp_timescale:true ptp_timesource:0 time_traceable:true]}]]

cat /tmp/yangToDbDataCreate.txt :
   -----------------------------------------------------------------
table name : PTP_INSTANCE
  key : 0
    NULL :NULL
-----------------------------------------------------------------
table name : PTP_PARENTDS
  key : GLOBAL
    clock_accuracy :0
    offset_scaled_log_variance :0
    grandmaster_priority1 :0
    grandmaster_priority2 :0
    observed_parent_clock_phase_change_rate :0
    observed_parent_offset_scaled_log_variance :65535
    port_number :0
    parent_stats :false
    clock_class :248
-----------------------------------------------------------------
table name : PTP_PORT
  key : Ethernet0
    port_state :initializing
    version_number :0
    log_min_pdelay_req_interval :0
    log_sync_interval :0
    delay_mechanism :e2e
    log_min_delay_req_interval :0
    underlying_interface :string
    announce_receipt_timeout :0
    log_announce_interval :0
    peer_mean_path_delay :0
-----------------------------------------------------------------
table name : PTP_TIMEPROPDS
  key : GLOBAL
    leap61 :true
    ptp_timescale :true
    ptp_timesource :0
    time_traceable :true
    current_utc_offset :0
    current_utc_offset_valid :true
    frequency_traceable :true
    leap59 :true
-----------------------------------------------------------------
table name : PTP_CURRENTDS
  key : GLOBAL
    offset_from_master :0
    steps_removed :0
    mean_path_delay :0
-----------------------------------------------------------------
table name : PTP_TC_PORT
  key : Ethernet0
    faulty_flag :false
    log_min_pdelay_req_interval :0
    peer_mean_path_delay :0
-----------------------------------------------------------------
table name : PTP_CLOCK
  key : GLOBAL
    clock_accuracy :0
    clock_class :248
    offset_scaled_log_variance :0
    domain_number :0
    priority1 :0
    tc_number_ports :0
    two_step_flag :true
    priority2 :0
    slave_only :true
    tc_delay_mechanism :e2e
    tc_primary_domain :0
    number_ports :0
-----------------------------------------------------------------
