### ISSUE TITLE
Unable to create the PortChannel using DELL cli.

### ISSUE THREAD

**Issue by KarthikKumarGoudBattula** [project-arlo/sonic-mgmt-framework#207]
sonic#
sonic# configure terminal
sonic(config)#
sonic(config)#
sonic(config)#
sonic(config)# interface PortChannel 100
sonic(conf-if-po100)#
sonic(conf-if-po100)#
sonic(conf-if-po100)#
sonic(conf-if-po100)# no shutdown
sonic(conf-if-po100)#
sonic(conf-if-po100)#
sonic(conf-if-po100)#
sonic(conf-if-po100)# exit
sonic(config)# exit
sonic#
sonic#
sonic#
sonic# show PortChannel summary
Flags:  D - Down
        U - Up (PortChannel)
----------------------------------------------------------------------------------------------------------------------------
Group               Port-Channel                  Type                Protocol       Member Ports
----------------------------------------------------------------------------------------------------------------------------
1                   PortChannel1      (D)         Eth                 LACP           'Ethernet56', 'Ethernet60'
12                  PortChannel12     (D)         Eth                 LACP
3                   PortChannel3      (D)         Eth                 LACP
sonic#
sonic#
sonic# configure terminal
sonic(config)#
sonic(config)# interface Ethernet 0
sonic(conf-if-Ethernet0)# channel-group 100
  mode  Set the LACP actor mode, default: ACTIVE
  <cr>

sonic(conf-if-Ethernet0)# channel-group 100
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)# exit
sonic(config)# interface Ethernet 1
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)# channel-group 100
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)# exit
sonic(config)#
sonic(config)#
sonic(config)# exit
sonic#
sonic#
sonic# show PortChannel summary
Flags:  D - Down
        U - Up (PortChannel)
----------------------------------------------------------------------------------------------------------------------------
Group               Port-Channel                  Type                Protocol       Member Ports
----------------------------------------------------------------------------------------------------------------------------
1                   PortChannel1      (D)         Eth                 LACP           'Ethernet56', 'Ethernet60'
12                  PortChannel12     (D)         Eth                 LACP
3                   PortChannel3      (D)         Eth                 LACP
sonic#
sonic#
sonic#

**Comment by bhavini-gada** [comment]
PortChannel code was merged yesterday to master. Please test with the latest code from master.
