### ISSUE TITLE
Vlan is in "Inactive" state even after giving "no shutdown" command.

### ISSUE THREAD

**Issue by KarthikKumarGoudBattula** [project-arlo/sonic-mgmt-framework#210]
The commands "shutdown/no shutdown" has no effect on the Vlan interface.

sonic#
sonic# configure terminal
sonic(config)#
sonic(config)#
sonic(config)# interface vlan 10
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# exit
sonic(config)# exit
sonic#
sonic#
sonic# show vlan 10
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive

sonic#
sonic#
sonic#
sonic#
sonic# configure terminal
sonic(config)#
sonic(config)#
sonic(config)# interface Ethernet 0
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)# switchport trunk allowed vlan 10
Success
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)# exit
sonic(config)# interface Ethernet 1
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)# switchport trunk allowed vlan 10
Success
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)#
sonic(conf-if-Ethernet1)# exit
sonic(config)# exit
sonic#
sonic#
sonic#
sonic# show Vlan 10
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive    T  Ethernet0
                       T  Ethernet1

sonic#
sonic#
sonic#
sonic# configure terminal
sonic(config)#
sonic(config)#
sonic(config)# interface vlan 10
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# no shutdown
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# exit
sonic(config)# exit
sonic#
sonic#
sonic#
sonic# show vlan 10
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive    T  Ethernet0
                       T  Ethernet1

sonic#
sonic#
sonic# configure terminal
sonic(config)#
sonic(config)#
sonic(config)#
sonic(config)# interface Vlan 10
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# no shutdown
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# exit
sonic(config)# exit
sonic#
sonic#
sonic#
sonic# show vlan 10
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive    T  Ethernet0
                       T  Ethernet1

sonic# show Vlan 10
Q: A - Access (Untagged), T - Tagged
NUM        Status      Q Ports
10         Inactive    T  Ethernet0
                       T  Ethernet1

sonic#
sonic#

**Comment by justinejose91** [comment]
Currently, SONiC doesn't have support for #shutdown/#no shutdown for vlan interface. I will hide that command.

**Comment by KarthikKumarGoudBattula** [comment]
When will we expect this support in SONiC?

**Comment by justinejose91** [comment]
Broadcom has to support this, if we want to have enable/disable operation support on VLAN interface. I already asked about this to @sachinholla , and he confirmed that DB schema is not supported for the respective operation.  That's the reason why, we decided to take off this command for VLAN interface. If Broadcom supports supports the vlanMgrD backend, enabling/disabling from mgmt-framework supports.

**Comment by justinejose91** [comment]
Please let me know if its not clear or if you have further questions.
