### ISSUE TITLE
CVL throws error on the translated data which got translated by the transformer

### ISSUE THREAD

**Issue by mbalachandar** [project-arlo/sonic-mgmt-framework#216]
Hi 

CVL throws error on the translated data which got translated by the transformer

```
I1029 12:49:11.246351  159692 db.go:745] setEntry: DoCVL for CREATE
I1029 12:49:11.246362  159692 db.go:561] doCVL: calling ValidateEditConfig: [{3 1 CFG_L2MC_TABLE|Vlan10 map[version:2 fast-leave:0 enabled:0 query-max-response-time:10 last-member-query-interval:1000]}]
libyang[0]: Invalid value "0" in "enabled" element. (path: /sonic-igmp-snooping:sonic-igmp-snooping/CFG_L2MC_TABLE/CFG_L2MC_TABLE_LIST[vlanname='Vlan10']/enabled)
E1029 12:49:11.246671  159692 db.go:567] doCVL: CVL Failure: 1001
E1029 12:49:11.246696  159692 db.go:571] doCVL: 1 1
I1029 12:49:11.246711  159692 db.go:582] doCVL: End: e: Translib Redis Error: CVL Failure: 1,001: {CFG_L2MC_TABLE_LIST 1,001 Invalid Field Received ['Vlan10'] 0 enabled CFG_L2MC_TABLE_LIST with keys['Vlan10' ] has field enabled with invalid value 0  }
E1029 12:49:11.246771  159692 common_app.go:403] REPLACE case - d.CreateEntry() failure
I1029 12:49:11.246776  159692 common_app.go:336] Returning from processCommon() - fail
E1029 12:49:11.246782  159692 common_app.go:158] Translib Redis Error: CVL Failure: 1,001: {CFG_L2MC_TABLE_LIST 1,001 Invalid Field Received ['Vlan10'] 0 enabled CFG_L2MC_TABLE_LIST with keys['Vlan10' ] has field enabled with invalid value 0  }
```
https://ent.box.com/s/bjmtawbbwwbwqdympm09us7y89oj1xh1

Thanks
Balachandar

**Comment by mbalachandar** [comment]
Even though i changed the bit to bool in the sonic yang for time being, still CVL throws error.
Please check it

I1029 14:33:53.879946  170119 db.go:745] setEntry: DoCVL for CREATE
**I1029 14:33:53.879958  170119 db.go:561] doCVL: calling ValidateEditConfig: [{3 1 CFG_L2MC_TABLE|Vlan10 map[version:2 enabled:false query-max-response-time:10 last-member-query-interval:1000 fast-leave:false]}]**
**libyang[0]: Leafref "/sonic-vlan:sonic-vlan/sonic-vlan:VLAN/sonic-vlan:VLAN_LIST/sonic-vlan:name" of value "Vlan10" points to a non-existing leaf. (path: /sonic-igmp-snooping:sonic-igmp-snooping/CFG_L2MC_TABLE/CFG_L2MC_TABLE_LIST[vlanname='Vlan10']/vlanname)**
E1029 14:33:53.888109  170119 db.go:567] doCVL: CVL Failure: 1014
E1029 14:33:53.888128  170119 db.go:571] doCVL: 1 1
I1029 14:33:53.888134  170119 db.go:582] doCVL: End: e: Translib Redis Error: CVL Failure: 1,014: {CFG_L2MC_TABLE_LIST 1,014 Dependent Data is missing ['Vlan10'] Vlan10 vlanname CFG_L2MC_TABLE_LIST with keys['Vlan10' ] has field vlanname with invalid value Vlan10  }
E1029 14:33:53.888202  170119 common_app.go:403] REPLACE case - d.CreateEntry() failure
I1029 14:33:53.888210  170119 common_app.go:336] Returning from processCommon() - fail
E1029 14:33:53.888216  170119 common_app.go:158] Translib Redis Error: CVL Failure: 1,014: {CFG_L2MC_TABLE_LIST 1,014 Dependent Data is missing ['Vlan10'] Vlan10 vlanname CFG_L2MC_TABLE_LIST with keys['Vlan10' ] has field vlanname with invalid value Vlan10  }
I1029 14:33:53.888238  170119 db.go:1365] AbortTx: Begin:
I1029 14:33:53.888246  170119 db.go:1377] AbortTx: No SET|DEL done, txState: txStateWatch
I1029 14:33:53.908084  170119 db.go:1413] AbortTx: End: e: <nil>
I1029 14:33:53.908109  170119 db.go:357] DeleteDB: Begin: d: { client: Redis<localhost:6379 db:4>, Opts: { DBNo: 4, InitIndicator: , TableNameSeparator: |, KeySeparator: | , DisableCVLCheck: false }, txState: txStateNone, tsCmds: [] }
E1029 14:33:53.908205  170119 handler.go:59] [REST-1] Translib error tlerr.TranslibCVLFailure - Translib Redis Error: CVL Failure: 1,014: {CFG_L2MC_TABLE_LIST 1,014 Dependent Data is missing ['Vlan10'] Vlan10 vlanname CFG_L2MC_TABLE_LIST with keys['Vlan10' ] has field vlanname with invalid value Vlan10  }
I1029 14:33:53.908484  170119 handler.go:72] [REST-1] Sending response 500, type=application/yang-data+json, data={"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"invalid-value"}]}}
I1029 14:33:53.908520  170119 router.go:128] [REST-1] PutOpenconfigInterfacesDeviationInterfacesInterfaceConfigIgmpSnoopingVersion took 61.307661ms

**Comment by dutta-partha** [comment]
If Vlan10 is not present in DB, CVL will throw error. I tested CREATE request with igmp snooping YANG model in CVL UT environment where Vlan10 is pre-created and it worked fine.

**Comment by bhavini-gada** [comment]
@dutta-partha @mbalachandar - Please close if it is no longer an issue.
