### ISSUE TITLE
Add support in goyang to support if-feature which is present in the nat module (IETF yang)

### ISSUE THREAD

**Issue by rvasanthm** [project-arlo/sonic-mgmt-framework#220]
Build fails for including ietf-nat.yang. Do we need to pull any patch?
Generating sonic-vlan.yin ...
../../../../models/yang/sonic/common/sonic-common.yang:6: warning: imported module "ietf-yang-types" not used
make[3]: Leaving directory '/sonic/src/sonic-mgmt-framework/src/cvl/testdata/schema'
make -C src/translib
make[3]: Entering directory '/sonic/src/sonic-mgmt-framework/src/translib'
cd ocbinds && /usr/local/go/bin/go  generate
F1023 23:40:39.856740    7461 generator.go:261] ERROR Generating Code: unknown type of entry Directory in findMappableEntities for /ietf-nat, unknown type of entry Directory in findMappableEntities for /ietf-nat
exit status 1
oc.go:22: running "sh": exit status 1
Makefile:54: recipe for target 'ocbinds/ocbinds.go' failed
make[3]: *** [ocbinds/ocbinds.go] Error 1

**Comment by bhavini-gada** [comment]
@sachin-brm - Any updates here ?

**Comment by bhavini-gada** [comment]
Plan is to define openconfig yang for NAT, hence closing this bug
