### ISSUE TITLE
Swagger Client : Throwing error when "show vlan" command is given 

### ISSUE THREAD

**Issue by KarthikKumarGoudBattula** [project-arlo/sonic-mgmt-framework#221]
root@sonic:/home/admin#
root@sonic:/home/admin# sonic-cli
sonic#
sonic# configure terminal
sonic(config)# no interface vlan 10
Success
sonic(config)#
sonic(config)# do show vlan
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-vlan.py", line 25, in <module>
    import sonic_vlan_client
ImportError: No module named sonic_vlan_client
sonic(config)#
sonic(config)#
sonic(config)#
sonic(config)# interface vlan 10
Success
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# do show vlan 10
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-vlan.py", line 25, in <module>
    import sonic_vlan_client
ImportError: No module named sonic_vlan_client
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)#
sonic(conf-if-Vlan10)# exit
sonic(config)# exit
sonic# show vlan 10
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-vlan.py", line 25, in <module>
    import sonic_vlan_client
ImportError: No module named sonic_vlan_client
sonic# show vlan
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-vlan.py", line 25, in <module>
    import sonic_vlan_client
ImportError: No module named sonic_vlan_client
sonic#

**Comment by justinejose91** [comment]
Looks like swagger-client for VLAN is broken in the latest build from master. I will check it.

**Comment by sachinholla** [comment]
@KarthikKumarGoudBattula , please add below line to your sonic-mgmt-framework/models/codegen.config file and rebuild the mgmt-framework docker.

PY_YANGAPI_CLIENTS += sonic-vlan

This is only a workaround; do not commit this change. We need to fix the vlan actioner script.

**Comment by justinejose91** [comment]
@sachinholla  Is it a known issue? Do we have a fix for it? Please provide insights into it.

**Comment by sachinholla** [comment]
hi @KarthikKumarGoudBattula, this is addressed now. Please try with latest
