### ISSUE TITLE
Throwing Traceback error when "show PortChannel summary" command is given

### ISSUE THREAD

**Issue by KarthikKumarGoudBattula** [project-arlo/sonic-mgmt-framework#225]
sonic#
sonic# configure terminal
sonic(config)# interface portchannel 100
Success
sonic(conf-if-po100)# do show PortChannel summary
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-portchannel.py", line 26, in <module>
    import sonic_portchannel_client
ImportError: No module named sonic_portchannel_client
sonic(conf-if-po100)#
sonic(conf-if-po100)# exit
sonic(config)#
sonic(config)# interface Ethernet 0
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)#
sonic(conf-if-Ethernet0)# channel-group 100
Success
sonic(conf-if-Ethernet0)# exit
sonic(config)# interface Ethernet 4
sonic(conf-if-Ethernet4)# channel-group 100
Success
sonic(conf-if-Ethernet4)# do show PortChannel summary
Traceback (most recent call last):
  File "/usr/sbin/cli/sonic-cli-portchannel.py", line 26, in <module>
    import sonic_portchannel_client
ImportError: No module named sonic_portchannel_client
sonic(conf-if-Ethernet4)#
sonic(conf-if-Ethernet4)#
sonic(conf-if-Ethernet4)#

**Comment by Tejaswi-Goel** [comment]
Looks like an issue from swagger-client, will check it.

**Comment by sachinholla** [comment]
hi @KarthikKumarGoudBattula, this is addressed now. Please try with latest

**Comment by bhavini-gada** [comment]
@sachinholla - Suggest to leave it open until the fix is merged to master.
