### ISSUE TITLE
mclag interface table - GetTablesToWatch returned empty slice

### ISSUE THREAD

**Issue by anand-kumar-subramanian** [project-arlo/sonic-mgmt-framework#235]
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236147      17 xlate_utils.go:297] module name = sonic-mclag
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236280      17 common_app.go:280] Result Tables List[MCLAG_INTF_TABLE]
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-**server E1031 22:52:17.236422      17 common_app.go:285] Failure to get Tables to watch for module sonic-mclag
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server E1031 22:52:17.236550      17 handler.go:59] [REST-58] Translib error *errors.errorString - GetTablesToWatch returned empty slice**

Logs:

Oct 31 22:52:17.059788 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.054336      17 handler.go:47] [REST-58] PATCH /restconf/data/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST=4,PortChannel60; content-len=139                                                                                                                                                                              
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.058335      17 handler.go:134] [REST-58] Content-type=application/yang-data+json; data={                              
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server   "sonic-mclag:MCLAG_INTF_LIST": [                                                                                                  
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server     {                                                                                                                                
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server       "if_id": "4",                                                                                                                  
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server       "if_name": "PortChannel60",                                                                                                    
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server       "if_type": "PortChannel"                                                                                                      
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server     }                                                                                                                                
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server   ]                                                                                                                                  
Oct 31 22:52:17.065495 sonic INFO mgmt-framework#supervisord: rest-server }                                                                                                                                    
Oct 31 22:52:17.068784 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.067785      17 handler.go:55] [REST-58] Translated path = /sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]                                                                                                                                                                                  
Oct 31 22:52:17.072376 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.070800      17 translib.go:217] Update request received with path =/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.071074      17 translib.go:218] Update request received with payload ={
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server   "sonic-mclag:MCLAG_INTF_LIST": [
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server     {
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server       "if_id": "4",
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server       "if_name": "PortChannel60",
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server       "if_type": "PortChannel"
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server     }
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server   ]
Oct 31 22:52:17.076751 sonic INFO mgmt-framework#supervisord: rest-server }
Oct 31 22:52:17.080794 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.078778      17 app_interface.go:130] getAppModule called for path =/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]
Oct 31 22:52:17.089219 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.088655      17 app_interface.go:137] found the entry in the map for path =/sonic-
Oct 31 22:52:17.093368 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.088972      17 app_interface.go:165] cast to appInterface worked&{<nil> <nil> <nil> map[] []}
Oct 31 22:52:17.093368 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.091683      17 request_binder.go:287] pathList[i] name:"sonic-mclag"
Oct 31 22:52:17.093368 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.092040      17 request_binder.go:287] pathList[i] name:"MCLAG_INTF_TABLE"
Oct 31 22:52:17.096844 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.092248      17 request_binder.go:294] modified path is: elem:<name:"sonic-mclag" > elem:<name:"MCLAG_INTF_TABLE" >
Oct 31 22:52:17.104907 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.104531      17 common_app.go:64] initialize:path =/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]
Oct 31 22:52:17.112129 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.104889      17 db.go:333] NewDB: Init indication not requested
Oct 31 22:52:17.112129 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.111024      17 common_app.go:83] translateUpdate:path =/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]
Oct 31 22:52:17.112129 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.111199      17 common_app.go:252] translateCRUDCommon:path =/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]
Oct 31 22:52:17.232163 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.231607      17 xlate.go:272] UPDATE case
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.232010      17 xlate_to_db.go:371] Update/replace req: path("/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]").
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.234727      17 xlate_to_db.go:281] Fill data for list uri()
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.235015      17 xlate_to_db.go:216] Found non-nil yang entry in xDbSpecMap for field xpath = MCLAG_INTF_TABLE/if_type
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server E1031 22:52:17.235191      17 xlate_to_db.go:459] DBMapCreate req failed for oper ("4") path("/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]") error ("<nil>").
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.235333      17 xlate_to_db.go:373] Update/replace req: path("/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60]") result("map[MCLAG_INTF_TABLE:map[4|PortChannel60:"if_type": "PortChannel"
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server ]]").
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server map[MCLAG_INTF_TABLE:map[4|PortChannel60:"if_type": "PortChannel"
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server ]]
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.235825      17 common_app.go:257] transformer.XlateToDb() returnedmap[MCLAG_INTF_TABLE:map[4|PortChannel60:"if_type": "PortChannel"
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server ]]
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.235987      17 xlate.go:387] received uri /sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST[if_id=4][if_name=PortChannel60] to extract module name from
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236147      17 xlate_utils.go:297] module name = sonic-mclag
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236280      17 common_app.go:280] Result Tables List[MCLAG_INTF_TABLE]
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server E1031 22:52:17.236422      17 common_app.go:285] Failure to get Tables to watch for module sonic-mclag
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server E1031 22:52:17.236550      17 handler.go:59] [REST-58] Translib error *errors.errorString - GetTablesToWatch returned empty slice
Oct 31 22:52:17.237005 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236756      17 handler.go:72] [REST-58] Sending response 500, type=application/yang-data+json, data={"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"operation-failed"}]}}
Oct 31 22:52:17.238193 sonic INFO mgmt-framework#supervisord: rest-server I1031 22:52:17.236917      17 router.go:128] [REST-58] PatchSonicMclagSonicMclagMclagIntfTableMclagIntfList took 182.622457ms
^CUser Aborted - Ctrl+C !
Command execution is failed, cmd:[sudo tail -F /var/log/syslog], error:[Errno 3] No such process

curl request
curl -X PATCH "https://10.59.142.85/restconf/data/sonic-mclag:sonic-mclag/MCLAG_INTF_TABLE/MCLAG_INTF_LIST=4,PortChannel60" -H "accept: application/yang-data+json" -H "Content-Type: application/yang-data+json" -d "{ \"sonic-mclag:MCLAG_INTF_LIST\": [ { \"if_id\": \"4\", \"if_name\": \"PortChannel60\", \"if_type\": \"PortChannel\" } ]}"
sonic yang file
module sonic-mclag {                                                                                                                                        
        namespace "http://github.com/Azure/sonic-mclag";                                                                                                    
        prefix smclag;                                                                                                                                      
        yang-version 1.1;                                                                                                                                    

        import ietf-yang-types {
                prefix yang;    
        }                      

        import ietf-inet-types {
                prefix inet;    
        }                      

    import sonic-portchannel {
        prefix spc;          
    }                        

        organization
                "SONiC";

        contact
                "SONiC";

        description
                "SONIC VXLAN";

        revision 2019-10-01 {
                description  
                        "Initial revision.";
        }                                  

        container sonic-mclag {

        container MCLAG {

            list MCLAG_LIST {
                key "id";    
                max-elements 1;

                leaf id {
                    type uint16 {
                        range "1..4095" {
                            error-message "MCLAG Domain ID out of range";
                        }                                                
                    }                                                    
                }                                                        

                leaf local_ip {
                    type inet:ipv4-address;
                }
                leaf peer_ip {
                    type inet:ipv4-address;
                }
                leaf peer_link {
                    type string;
                }
                leaf keepalive_time {
                    type uint16 {
                        range "1..60" {
                            error-message "MCLAG Domain keepalive interval out of range";
                        }
                    }
                }
                leaf session_timeout {
                    type uint16 {
                        range "1..3600" {
                            error-message "MCLAG Domain session timeout out of range";
                        }
                    }
                }
            }
        }

        container MCLAG_INTF_TABLE {

            list MCLAG_INTF_LIST {
                key "if_id if_name";

                leaf if_id {
                    type leafref {
                        path "../../../MCLAG/MCLAG_LIST/id";
                    }
                }

                leaf if_name {
                    type leafref {
                        path "/spc:sonic-portchannel/spc:PORTCHANNEL/spc:PORTCHANNEL_LIST/spc:name";
                    }
                }

                leaf if_type {
                    type string;
                }
            }
        }
    }
}

**Comment by amrutasali** [comment]
Analysis in progress

**Comment by amrutasali** [comment]
Please assign to Partha or appropriate person in CVL layer for further analysis since the CVL layer is giving incorrect info.

From our analysis we found that the CVL API - cvlSess.GetOrderedTables("sonic-mclag") gives us incorrect table Name- MCLAG_INTF instead of MCLAG_INTF**_TABLE** which goes into a map that transformer maintains to fetch tables to watch.

The sonic model table info maintained by CVL layer shows following where the redis-table name does not match the map key(table name)
   572:	
(dlv) p modelInfo.tableInfo
map[string]*cvl.modelTableInfo [
         ........
	"**MCLAG_INTF**": *{
		dbNum: 4,
		modelName: "sonic-mclag",
		redisTableName: "**MCLAG_INTF_TABLE**",
		module: *(*"cvl/internal/yparser.YParserModule")(0x2790130),
		keys: []string len: 2, cap: 2, ["if_id","if_name"],
		redisKeyDelim: "|",
		redisKeyPattern: "MCLAG_INTF|{if_id}|{if_name}",
		redisTableSize: -1,
		mapLeaf: []string len: 0, cap: 0, nil,
		leafRef: map[string][]string [...],
		mustExp: map[string]string nil,
		tablesForMustExp: map[string]cvl.CVLOperation nil,
		refFromTables: []cvl.tblFieldPair len: 0, cap: 0, nil,},

**Comment by anand-kumar-subramanian** [comment]
Following is the sonic yang for this issue
module sonic-mclag {                                                                                                                                        
        namespace "http://github.com/Azure/sonic-mclag";                                                                                                    
        prefix smclag;                                                                                                                                      
        yang-version 1.1;                                                                                                                                    

        import ietf-yang-types {
                prefix yang;    
        }                      

        import ietf-inet-types {
                prefix inet;    
        }                      

    import sonic-portchannel {
        prefix spc;          
    }                        

        organization
                "SONiC";

        contact
                "SONiC";

        description
                "SONIC VXLAN";

        revision 2019-10-01 {
                description  
                        "Initial revision.";
        }                                  

        container sonic-mclag {

        container MCLAG {

            list MCLAG_LIST {
                key "id";    
                max-elements 1;


                leaf id {
                    type string;
                }              

                leaf local_ip {
                    type inet:ipv4-address;
                }
                leaf peer_ip {
                    type inet:ipv4-address;
                }
                leaf peer_link {
                    type string;
                }
                leaf keepalive_time {
                    type uint16 {
                        range "1..60" {
                            error-message "MCLAG Domain keepalive interval out of range";
                        }
                    }
                }
                leaf session_timeout {
                    type uint16 {
                        range "1..3600" {
                            error-message "MCLAG Domain session timeout out of range";
                        }
                    }
                }
            }
        }

        container MCLAG_INTF_TABLE {

            list MCLAG_INTF_LIST {
                key "if_id if_name";

                leaf if_id {
                    type leafref {
                        path "../../../MCLAG/MCLAG_LIST/id";
                    }
                }

                leaf if_name {
                    type leafref {
                        path "/spc:sonic-portchannel/spc:PORTCHANNEL/spc:PORTCHANNEL_LIST/spc:name";
                    }
                }

                leaf if_type {
                    type string;
                }
            }
        }
    }

**Comment by anand-kumar-subramanian** [comment]
Partha,

As per comments from Amruta, CVL is returning table name MCLAG_INTF instead of MCLAG_INTF_TABLE. Can you look into this?

**Comment by dutta-partha** [comment]
@amrutasali @anand-kumar-subramanian The following SONiC YANG is not following the guideline and hence error.

```
 container MCLAG_INTF_TABLE {

        list MCLAG_INTF_LIST {  ----> should be MCLAG_INTF_TABLE_LIST 
            key "if_id if_name";

```

BTW, is MCLAG_INTF_TABLE a new table ? Why we are appending "_TABLE" ? It is implicit that it is a table in the context.

**Comment by amrutasali** [comment]
@anand-kumar-subramanian - the yang model needs to be changed as per Partha's comment
