### ISSUE TITLE
Error returned from backend as tlerr instance is ignored by xfmr

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#239]
Eg - For adding a member port to Invalid VLAN should be displayed as "Invalid VLAN: <id>" at the front-end. Currently, backend returns tlerr instance ("Invalid VLAN: <id>"), but xfmr ignores the error message.

**Comment by Tejaswi-Goel** [comment]
Issue to be further tracked on JIRA. So closing it.
