### ISSUE TITLE
Translib support for subscribe operation

### ISSUE THREAD

**Issue by seiferteric** [project-arlo/sonic-mgmt-framework#24]
For implementing gNMI Subscribe functionality, we need to be able to subscribe to the set of keys that an object uses for create, update and delete actions. Currently I see in translib that Subscribe is not implemented/supported. Is there a plan to start this implementation?

**Comment by anand-kumar-subramanian** [comment]
Yes support for subscribe in translib is coming, but this will only support ON_CHANGE subscriptions. All other subscription types should be handled by gNMI server using the get method of translib.

**Comment by jeffyin-dell** [comment]
@anand-kumar-subramanian @seiferteric -- is this still an open issue? can we close it?
