### ISSUE TITLE
Transformer get is failing in UnMarshal saying the key type is not matching

### ISSUE THREAD

**Issue by anand-kumar-subramanian** [project-arlo/sonic-mgmt-framework#241]
Transformer get is failing in UnMarshal saying the type is not matching. 

Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server E1101 18:55:39.857001      17 common_app.go:220] ocbinds.Unmarshal()  failed. error:got string type for field id, expect float64
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server E1101 18:55:39.858649      17 handler.go:59] [REST-5] Translib error *errors.errorString - got string type for field id, expect float64

Config through transformer is going through fine. 
Seems the issue happens only when the DBToYang conversion for id(uint16)
Also that it complains that it is expecting float64 in ocbinds, but the ocbinds has uint16(as defined in the sonic yang)
If the key for the MLAG table is string this issue is not seen.

REST request:
curl -X GET "https://10.59.142.85/restconf/data/sonic-mclag:sonic-mclag/MCLAG" -H "accept: application/yang-data+json"

Logs:
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.851145      17 router.go:122] [REST-5] Recevied GetSonicMclagSonicMclagMclag request from 10.58.47.248:52420
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.851573      17 handler.go:47] [REST-5] GET /restconf/data/sonic-mclag:sonic-mclag/MCLAG; content-len=0
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.851794      17 handler.go:92] [REST-5] No body
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.851940      17 handler.go:55] [REST-5] Translated path = /sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.852072      17 translib.go:420] Received Get request for path = /sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.852198      17 app_interface.go:130] getAppModule called for path =/sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.852320      17 app_interface.go:137] found the entry in the map for path =/sonic-
Nov  1 18:55:39.852765 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.852443      17 app_interface.go:165] cast to appInterface worked&{<nil> <nil> <nil> map[] []}
Nov  1 18:55:39.854724 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.852740      17 common_app.go:64] initialize:path =/sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.854724 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.854237      17 db.go:333] NewDB: Init indication not requested
Nov  1 18:55:39.854724 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.854399      17 common_app.go:111] translateGet:path =/sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.854724 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.854557      17 common_app.go:182] processGet:path =/sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.857045 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.855621      17 xlate.go:298] received xpath =/sonic-mclag:sonic-mclag/MCLAG
Nov  1 18:55:39.857045 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.855872      17 xlate.go:94] key separator for table MCLAG in Db 4 is |
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856533      17 xlate.go:94] key separator for table MCLAG in Db 4 is |
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856744      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(id)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856755      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(local_ip)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856764      17 xlate_from_db.go:128] Received FieldXpath MCLAG/local_ip, yngTerminalNdDtType string and Db field value 1.1.1.1 to be converted to yang data-type.
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856774      17 xlate_from_db.go:156] Yenum/Ystring/Yunion(having all members as strings) type for yangXpath MCLAG/local_ip
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856782      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(peer_ip)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856789      17 xlate_from_db.go:128] Received FieldXpath MCLAG/peer_ip, yngTerminalNdDtType string and Db field value 2.2.2.2 to be converted to yang data-type.
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856797      17 xlate_from_db.go:156] Yenum/Ystring/Yunion(having all members as strings) type for yangXpath MCLAG/peer_ip
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856804      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(peer_link)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856811      17 xlate_from_db.go:128] Received FieldXpath MCLAG/peer_link, yngTerminalNdDtType string and Db field value PortChannel30 to be converted to yang data-type.
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856820      17 xlate_from_db.go:156] Yenum/Ystring/Yunion(having all members as strings) type for yangXpath MCLAG/peer_link
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856827      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(keepalive_time)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856834      17 xlate_from_db.go:128] Received FieldXpath MCLAG/keepalive_time, yngTerminalNdDtType uint16 and Db field value 15 to be converted to yang data-type.
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856843      17 xlate_from_db.go:267] tbl(MCLAG), k(4), yc(session_timeout)
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856850      17 xlate_from_db.go:128] Received FieldXpath MCLAG/session_timeout, yngTerminalNdDtType uint16 and Db field value 30 to be converted to yang data-type.
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.856937      17 xlate.go:358] Payload generated:{"MCLAG_LIST":[{"id":"4","keepalive_time":15,"local_ip":"1.1.1.1","peer_ip":"2.2.2.2","peer_link":"PortChannel30","session_timeout":30}]}
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server E1101 18:55:39.857001      17 common_app.go:220] ocbinds.Unmarshal()  failed. error:got string type for field id, expect float64
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server E1101 18:55:39.858649      17 handler.go:59] [REST-5] Translib error *errors.errorString - got string type for field id, expect float64
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.860370      17 handler.go:72] [REST-5] Sending response 500, type=application/yang-data+json, data={"ietf-restconf:errors":{"error":[{"error-type":"application","error-tag":"operation-failed"}]}}
Nov  1 18:55:39.861591 sonic INFO mgmt-framework#supervisord: rest-server I1101 18:55:39.860392      17 router.go:128] [REST-5] GetSonicMclagSonicMclagMclag took 8.8529ms

sonic yang
module sonic-mclag {                                                                                                                                              
        namespace "http://github.com/Azure/sonic-mclag";                                                                                                          
        prefix smclag;                                                                                                                                            
        yang-version 1.1;                                                                                                                                          

        import ietf-yang-types {
                prefix yang;    
        }                      

        import ietf-inet-types {
                prefix inet;    
        }                      

    import sonic-portchannel {
        prefix spc;          
    }                        

        organization
                "SONiC";

        contact
                "SONiC";

        description
                "SONIC VXLAN";

        revision 2019-10-01 {
                description  
                        "Initial revision.";
        }                                  

        container sonic-mclag {

        container MCLAG {

            list MCLAG_LIST {
                key "id";    
                max-elements 1;

                leaf id {
                    type uint16 {
                        range "1..4095" {
                            error-message "MCLAG Domain ID out of range";
                        }                                                
                    }                                                    
                }                                                        

                leaf local_ip {
                    type inet:ipv4-address;
                }
                leaf peer_ip {
                    type inet:ipv4-address;
                }
                leaf peer_link {
                    type string;
                }
                leaf keepalive_time {
                    type uint16 {
                        range "1..60" {
                            error-message "MCLAG Domain keepalive interval out of range";
                        }
                    }
                }
                leaf session_timeout {
                    type uint16 {
                        range "1..3600" {
                            error-message "MCLAG Domain session timeout out of range";
                        }
                    }
                }
            }
        }

        container MCLAG_INTF_TABLE {

            list MCLAG_INTF_LIST {
                key "if_id if_name";

                leaf if_id {
                    type leafref {
                        path "../../../MCLAG/MCLAG_LIST/id";
                    }
                }

                leaf if_name {
                    type leafref {
                        path "/spc:sonic-portchannel/spc:PORTCHANNEL/spc:PORTCHANNEL_LIST/spc:name";
                    }
                }

                leaf if_type {
                    type string;
                }
            }
        }
    }
}

**Comment by amrutasali** [comment]
Available in transformer-phase-2 branch - fix for conversion from  Db type(string) to yang data-type(uint16) for key leaf "id"
