### ISSUE TITLE
Delete operation on acls with translib is not completely deleting data.

### ISSUE THREAD

**Issue by seiferteric** [project-arlo/sonic-mgmt-framework#40]
I have noticed in gNMI, but has been confirmed outside of gNMI as well. I create ACLs using the test data, then I issue a delete for the openconfig-acl:acl path, then I do a get on the same path and not all of the data is deleted. Then I issue a second delete, then all of the data is deleted.

**Comment by maheshwari-mayank** [comment]
Issue is fixed.
