### ISSUE TITLE
ACL table delete fails (CVL failure)

### ISSUE THREAD

**Issue by Tejaswi-Goel** [project-arlo/sonic-mgmt-framework#50]
sonic(config-ipv4-acl)# do show ip access-lists
ip access-list acl2

sonic(config)# no ip access-list acl2
Exception when calling OpenconfigAclApi->delete_openconfig_acl_acl_acl_sets_acl_set : (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Thu, 25 Jul 2019 20:42:05 GMT', 'Content-Length': '40', 'Content-Type': 'application/yang-data+json; charset=UTF-8'})
HTTP response body: Translib Redis Error: CVL Failure: 1,002
sonic(config)#

**Comment by sachinholla** [comment]
@dutta-partha , I dont see this issue on broadcom branch now. Please check if the fix has been merged to master.

**Comment by Tejaswi-Goel** [comment]
Pull the latest changes and created new sonic image, the issue is no more seen on latest image, so closing this issue.
