### ISSUE TITLE
When requesting an unsupported path, we should return an error.

### ISSUE THREAD

**Issue by seiferteric** [project-arlo/sonic-mgmt-framework#53]
https://github.com/project-arlo/sonic-mgmt-framework/blob/45668bbfd70a9dccdecdcf0c0558d3670f8f57da/src/translib/intf_app.go#L320

Currently in gNMI and restconf, requesting `/openconfig-interfaces:interfaces/interface[name=Ethernet0]/config/mtu` will return an empty response with no error. Looking at the above code, we simply log that the path is not supported, but I think we should return an error indicating that the path is not supported.

**Comment by justinejose91** [comment]
Pull-request raised.
https://github.com/project-arlo/sonic-mgmt-framework/pull/54
Individual attributes get support development is in progress.

**Comment by justinejose91** [comment]
Merged, closing it.
