### ISSUE TITLE
Adding tagged port to VLAN that already has another tagged port as member throws CVL error.

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#84]
Sequence to Reproduce:
1. Create VLAN 4- works
2. Add a tagged/untagged port (Ethernet12) to VLAN 4- works
3. Add second tagged port (Ethernet16) to same VLAN 4 - CVL throws error
Error occurs when I try to create VLAN_MEMBER table entry in Config -DB. Same is mentioned by @dutta-partha in the CVL slack channel as well. Let me know if you need any info.

Please have a look at CVL error logs below:
[cvl_logs.txt](https://github.com/project-arlo/sonic-mgmt-framework/files/3552234/cvl_logs.txt)

**Comment by justinejose91** [comment]
Fix from @asha-behera works, please raise pull-request.

**Comment by dutta-partha** [comment]
@justinejose91 the changes are available in master branch now. Can you please test this.

**Comment by justinejose91** [comment]
Its fixed, Thanks @dutta-partha and @asha-behera
