### ISSUE TITLE
CVL throws error when trying to configure IP address

### ISSUE THREAD

**Issue by justinejose91** [project-arlo/sonic-mgmt-framework#86]
Reproduce Steps:
1. Please apply the patch provided to intf_app.go. When system comes up for the first time, Inorder to configure IP, we will first create INTERFACE|Ethernet84, followed by INTERFACE|Ethernet84|84.2.3.4/24. CVL throws failure in the first entry creation, ie INTERFACE|Ethernet84. (edited) 
Rest Request: {"openconfig-if-ip:config": {"ip": "84.2.3.4", "prefix-length": 24}}
KeyPath = [Ethernet84]

Following is the patch need to be applied to intf_app.go
[diff.txt](https://github.com/project-arlo/sonic-mgmt-framework/files/3580515/diff.txt)
Attaching the CVL failure logs.
[cvl_failure_logs.txt](https://github.com/project-arlo/sonic-mgmt-framework/files/3580520/cvl_failure_logs.txt)

**Comment by justinejose91** [comment]
For IP address addition, we basically need to make 2 entries, one is INTERFACE|Ethernet84, followed by the second entry INTERFACE|Ethernet84|84.2.3.4/24. If we don't add the first entry and just the second entry, basically, the configuration wont get pushed southwards.
Once the IP address is configured or if the Interface comes up with IP configured, then we don't need to create first entry. In all other cases, we need it.

**Comment by dutta-partha** [comment]
This issue can't be fixed until modelling of such table (i.e. with optional key) is finalized in SONiC YANG development guideline.

Due to my github account problem I am not able to assign this issue to myself.

**Comment by justinejose91** [comment]
Do we have any other way to fix this problem, like disabling CVL check for first createEntry query? Because, this bug somehow needs to be resolved with some workaround, unless system comes up default with all these entries.

**Comment by jeffyin-dell** [comment]
Assigned to @dutta-partha -- @sachin-brm can you help prioritize, as this is related to two other issues

**Comment by asha-behera** [comment]
CVL issue fixed and REDIS is also getting populated .
Please check REDIS DB output

127.0.0.1:6379[4]> keys INTERFACE*
1) "INTERFACE|Ethernet4|20.9.9.19/8"
2) "INTERFACE|Ethernet4|5.5.5.5/8"
3) "INTERFACE|Ethernet5|1001::1/64"

**Comment by justinejose91** [comment]
I will verify this.
