### ISSUE TITLE
IP address not set with Ethernet

### ISSUE THREAD

**Issue by mingjunzhang2019** [project-arlo/sonic-mgmt-framework#90]
Platform: Z9100, Build Label: 299

sonic(conf-if-Ethernet4)# ip address 20.9.9.9/8
Success
sonic(conf-if-Ethernet4)#
sonic(conf-if-Ethernet4)#
sonic(conf-if-Ethernet4)# do show interface Ethernet 4
Ethernet4 is down, line protocol is down
Hardware is Eth
Interface index is 2
Mode of IPV4 address assignment: not-set
Mode of IPV6 address assignment: not-set
IP MTU 9100 bytes

**Comment by mingjunzhang2019** [comment]
Justine is working on this issue.

**Comment by justinejose91** [comment]
As discussed, still waiting for the fix from Broadcom.

**Comment by justinejose91** [comment]
This issue is same as #86.

**Comment by jeffyin-dell** [comment]
Closing since it's a duplicate
