### ISSUE TITLE
IP and IPV6 address assignment fields displaying "not-set" even though ip is configured in sonic-cli

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#95]
Problem Description/Summary :
--------------------------------------------
 IP and IPV6 address assignment fields displaying "not-set" even though ip is configured in sonic-cli

Expected Behavior : 
------------------------
Mode of IPV4 address assignment and Mode of IPV6 address assignment fields should display as manual when IP address configured on the interface

Topology :
------------
DUT

Steps to Repro :
--------------------
1) Go to sonic-cli and configure IP and IPV6 addresses on the interface
2) Issue the command "show interface Ethernet" for the configured IP address interface.
3) Observing that "Mode of IPV4 address assignment and Mode of IPV6 address assignment" displaying as not-set instead of manual
 
sonic(conf-if-Ethernet0)# ip address 192.168.1.1/24
Success
sonic(conf-if-Ethernet0)# exit
sonic(config)# exit
sonic# show interface Ethernet 0
Ethernet0 is up, line protocol is up
Hardware is Eth
Interface index is 0
Mode of IPV4 address assignment: not-set
Mode of IPV6 address assignment: not-set
IP MTU 9100 bytes
LineSpeed , Auto-negotiation off
Input statistics:
30 packets, 6904 octets
30 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 30 discarded
Output statistics:
32 packets, 7172 octets
32 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 0 discarded
sonic#
sonic#
sonic#
sonic#
sonic#
sonic#
sonic#
sonic# show interface Ethernet 0
Ethernet0 is up, line protocol is up
Hardware is Eth
Interface index is 0
Mode of IPV4 address assignment: not-set
Mode of IPV6 address assignment: not-set
IP MTU 9100 bytes
LineSpeed , Auto-negotiation off
Input statistics:
30 packets, 6904 octets
30 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 30 discarded
Output statistics:
32 packets, 7172 octets
32 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 0 discarded
sonic#
sonic#
sonic#
sonic#
sonic# configure terminal
sonic(config)# interface Ethernet 68
sonic(conf-if-Ethernet68)#
sonic(conf-if-Ethernet68)# ipv6 address 1001::1/64
Success
sonic(conf-if-Ethernet68)# exit
sonic(config)# exit
sonic# show
interface ip lldp platform system
sonic# show interface Ethernet 68
Ethernet68 is up, line protocol is up
Hardware is Eth
Interface index is 17
Mode of IPV4 address assignment: not-set
Mode of IPV6 address assignment: not-set
IP MTU 9100 bytes
LineSpeed 10GB, Auto-negotiation off
Input statistics:
0 packets, 0 octets
0 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 0 discarded
Output statistics:
33 packets, 7409 octets
33 Multicasts, 0 Broadcasts, 0 Unicasts
0 error, 0 discarded
sonic#

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------
 Every time

**Comment by jeffyin-dell** [comment]
Issue is related to #86, for which we're waiting on a fix.

**Comment by justinejose91** [comment]
This issue is exactly same as #86 . Root cause is the same.

**Comment by dutta-partha** [comment]
CVL fix for IP configuration is available in master branch (PR #118). @justinejose91 Can you please check this.

**Comment by justinejose91** [comment]
Works fine.
