### ISSUE TITLE
Line speed not displaying any value in sonic-cli

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#96]
Problem Description/Summary :
--------------------------------------------
Line speed not displaying any value in sonic-cli

Expected Behavior : 
------------------------
Line speed should display the speed

Topology :
------------
DUT

Steps to Repro :
--------------------
1) Go to sonic-cli and execute the command "show interface Ethernet <port_number>
2) Observing that Line speed not displaying any value 

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------
 Yes

**Comment by jeffyin-dell** [comment]
@sachin-brm -- 
(1) what platform(s)? 
(2) Also, please display the command output log.
(3) "sonic-cli" refers to the new clish-based CLI, or click-based?

**Comment by justinejose91** [comment]
Pull-request raised.

**Comment by jeffyin-dell** [comment]
Fixed by https://github.com/project-arlo/sonic-mgmt-framework/pull/109
