### ISSUE TITLE
Interface speed incorrect in 'sonic-cli' output

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#97]
Problem Description/Summary :
--------------------------------------------
Interface speed incorrect in 'sonic-cli' output

Expected Behavior : 
------------------------
Interface speed value should be consistent across all CLI.

Topology :
------------
DUT

Steps to Repro :
--------------------
1. Load the latest build and breakout a port to 4x10 using breakout script.
2. Compare the 'show interaface status' from click based CLI and the from within 'sonic-cli' KLISH based o/p.
3. Observe that the values are not in sync:
CLIK based:
```
Ethernet68 101 10G 9100 tenGigE18:1 routed up up QSFP+ or later N/A
Ethernet69 102 10G 9100 tenGigE18:2 routed up up QSFP+ or later N/A
Ethernet70 103 10G 9100 tenGigE18:3 routed down down QSFP+ or later N/A
Ethernet71 104 10G 9100 tenGigE18:4 routed down down QSFP+ or later N/A
Ethernet72 105 10G 9100 tenGigE19:1 routed down down N/A N/A
Ethernet73 106 10G 9100 tenGigE19:2 routed down down N/A N/A
Ethernet74 107 10G 9100 tenGigE19:3 routed down down N/A N/A
Ethernet75 108 10G 9100 tenGigE19:4 routed down down N/A N/A
Ethernet76 109,110,111,112 100G 9100 hundredGigE20 routed down down N/A N/A
```
 
sonicl-cli:
(All interfaces after the first 10GB interfaces are listed as 10G even though they are 100G in other CLI)
```
Ethernet68 - up up 10GB 9100
Ethernet69 - up up 10GB 9100
Ethernet70 - down down 10GB 9100
Ethernet71 - down down 10GB 9100
Ethernet72 - down down 10GB 9100

Ethernet73 - down down 10GB 9100
Ethernet74 - down down 10GB 9100
Ethernet75 - down down 10GB 9100
```
(above output was truncated, but Ethernet76 was also displaying 10GB instead of the expected 100GB)

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------
Yes. Everytime.

**Comment by justinejose91** [comment]
Couple of questions:
Which platform is this?
Could you provide the output before breakout and after breakout for SONiC-CLI and clik based CLI?
Can you provide the exact port_config.ini file changes for breakout?

**Comment by jeffyin-dell** [comment]
@sachin-brm really could use your help providing more info on the issue so that we can resolve it quickly.

**Comment by justinejose91** [comment]
Pull-request raised.

**Comment by jeffyin-dell** [comment]
Fixed by https://github.com/project-arlo/sonic-mgmt-framework/pull/109
