### ISSUE TITLE
ON_CHANGE Streaming mode results in Invalid mode rpc error for /openconfig-lldp:lldp/interfaces/interface[name=Ethernet24]

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#98]
Problem Description/Summary :
--------------------------------------------
ON_CHANGE Streaming mode results in Invalid mode rpc error for /openconfig-lldp:lldp/interfaces/interface[name=Ethernet24]

Expected Behavior : 
------------------------
No RPC error.

 

3.5.1.5.2 STREAM Subscriptions
Stream subscriptions are long-lived subscriptions which continue to transmit updates relating to the set of paths that are covered within the subscription indefinitely.

A STREAM subscription is created by sending a SubscribeRequest message with the subscribe field containing a SubscriptionList message with the type specified as STREAM. Each entry within the Subscription message is specified with one of the following modes:

On Change (ON_CHANGE) - when a subscription is defined to be "on change", data updates are only sent when the value of the data item changes.
For all ON_CHANGE subscriptions, the target MUST first generate updates for all paths that match the subscription path(s), and transmit them. Following this initial set of updates, updated values SHOULD only be transmitted when their value changes.
A heartbeat interval MAY be specified along with an "on change" subscription - in this case, the value of the data item(s) MUST be re-sent once per heartbeat interval regardless of whether the value has changed or not.

Topology :
------------
DUT

Steps to Repro :
--------------------
1. Perform a ON_change subscription to LLDP entries on a specific interface:

./gnmi_cli -insecure -logtostderr -address 127.0.0.1:8080 -query_type s -streaming_type 1 -q /openconfig-lldp:lldp/interfaces/interface[name=Ethernet84] -v 0 -target OC-YANG

2. Observe that it results in RPC error as "ON_CHANGE Streaming mode invalid"

 

root@sonic:/# ./gnmi_cli -insecure -logtostderr -address 127.0.0.1:8080 -query_type s -streaming_type 1 -q /openconfig-lldp:lldp/interfaces/interface[name=Ethernet84] -v 0 -target OC-YANG
E0910 05:57:41.125038 318 gnmi_cli.go:185] sendQueryAndDisplay(ctx, {Addrs:[127.0.0.1:8080] AddressChains:[] Target:OC-YANG Replica:0 UpdatesOnly:false Queries:[[openconfig-lldp:lldp interfaces interface[name=Ethernet84]]] Type:stream Timeout:30s NotificationHandler:<nil> ProtoHandler:<nil> Credentials:<nil> TLS:0xe08940 Extra:map[] SubReq:<nil> Streaming_type:ON_CHANGE Streaming_sample_int:0 Heartbeat_int:0 Suppress_redundant:false}, &{PollingInterval:30s StreamingDuration:0s Count:0 countExhausted:false Delimiter:/ Display:0x8692b0 DisplayPrefix: DisplayIndent: DisplayType:group DisplayPeer:false Timestamp: DisplaySize:false Latency:false ClientTypes:[gnmi]}):
rpc error: code = InvalidArgument desc = ON_CHANGE Streaming mode invalid for /openconfig-lldp:lldp/interfaces/interface[name=Ethernet84]
root@sonic:/#

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------

 3/3

**Comment by GarrickHe** [comment]
@sachin-brm does this mode work on other URIs?

Will probably need to add support for this in the lldp app module...

Thanks,
Garrick

**Comment by GarrickHe** [comment]
@sachin-brm Did some digging. Are you using the latest version of SONiC management-framework? There is a PR merged that should support what you're doing:

https://github.com/project-arlo/sonic-mgmt-framework/pull/76

The Unit-test on the PR shows:

```
root@sonic:~# ./gnmi_cli -insecure -logtostderr -address 127.0.0.1:8080 -query_type s -streaming_type 1 -q /openconfig-lldp:lldp/interfaces/interface[name=Ethernet0] -v 0 -target OC-YANG
{
  "OC-YANG": {
    "openconfig-lldp:lldp": {
      "interfaces": {
        "interface": {
          "Ethernet0": "{\"openconfig-lldp:interface\":[{\"name\":\"Ethernet0\",\"neighbors\":{\"neighbor\":[{\"id\":\"Ethernet0\"}]}}]}"
        }
      }
    }
  }
}
{
  "OC-YANG": {
    "openconfig-lldp:lldp": {
      "interfaces": {
        "interface": {
          "Ethernet0": "{\"openconfig-lldp:interface\":[{\"name\":\"Ethernet0\",\"neighbors\":{\"neighbor\":[{\"capabilities\":{\"capability\":[{\"name\":\"openconfig-lldp-types:REPEATER\",\"state\":{\"enabled\":false,\"name\":\"openconfig-lldp-types:REPEATER\"}}]},\"id\":\"Ethernet0\",\"state\":{\"id\":\"6\",\"port-id-type\":\"INTERFACE_NAME\"}}]}}]}"
        }
      }
    }
  }
}
{
  "OC-YANG": {
    "openconfig-lldp:lldp": {
      "interfaces": {
        "interface": {
          "Ethernet0": "{\"openconfig-lldp:interface\":[{\"name\":\"Ethernet0\",\"neighbors\":{\"neighbor\":[{\"capabilities\":{\"capability\":[{\"name\":\"openconfig-lldp-types:MAC_BRIDGE\",\"state\":{\"enabled\":true,\"name\":\"openconfig-lldp-types:MAC_BRIDGE\"}},{\"name\":\"openconfig-lldp-types:REPEATER\",\"state\":{\"enabled\":true,\"name\":\"openconfig-lldp-types:REPEATER\"}},{\"name\":\"openconfig-lldp-types:ROUTER\",\"state\":{\"enabled\":true,\"name\":\"openconfig-lldp-types:ROUTER\"}}]},\"id\":\"Ethernet0\",\"state\":{\"chassis-id\":\"34:17:eb:2c:d7:00\",\"chassis-id-type\":\"MAC_ADDRESS\",\"id\":\"6\",\"management-address\":\"\",\"port-description\":\"ethernet1/1/1:1\",\"port-id\":\"ethernet1/1/1:1\",\"port-id-type\":\"INTERFACE_NAME\",\"system-description\":\"Dell EMC Networking OS10 Enterprise.\\r\\nCopyright (c) 1999-2019 by Dell Inc. All Rights Reserved.\\r\\nSystem Description: OS10 Enterprise.\\r\\nOS Version: 10.4.9999EX.\\r\\nSystem Type: Z9100-ON\",\"system-name\":\"OS10\",\"ttl\":0}}]}}]}"
        }
      }
    }
  }
}
```

**Comment by seiferteric** [comment]
This commit 622788cb5d0d6942b4f2a1096c57e7ac78c693cc changed the behavior of HasSuffix function in path_utils.go. Before the Template included the name of the keys like "{name}" whereas after it did not: "{}". So this introduced bugs in code using the HasSuffix("{name"}) format which includes intf_app.go and lldp_app.go.

**Comment by jeffyin-dell** [comment]
@GarrickHe can you fix lldp_app.go to adapt to this new behavior?

**Comment by Tejaswi-Goel** [comment]
Was already looking into this issue, as Eric pointed out behavior of HasSuffix function changed, here is the fix to support that change and fix this bug: https://github.com/project-arlo/sonic-mgmt-framework/pull/104 
@seiferteric @jeff-yin @GarrickHe  please review it.
