### ISSUE TITLE
No response from telemetry on ON_change subscription to /openconfig-system:system

### ISSUE THREAD

**Issue by sachin-brm** [project-arlo/sonic-mgmt-framework#99]
Problem Description/Summary :
--------------------------------------------
No response from telemetry on ON_change subscription to /openconfig-system:system

Expected Behavior : 
------------------------
Initial updates should be provided even if the path does not support ON_Change.

Topology :
------------
DUT

Steps to Repro :
--------------------
1. Initiate an ON_Change subscription to /openconfig-system:system YANG model.

2. Observe that there is no response from telemetry.

3. telemetry.log shows that path was never resolved unlike in the case of "sample" mode.

 

root@sonic:/# ./gnmi_cli -insecure -logtostderr -address 127.0.0.1:8080 -query_type s -streaming_type 1 -q /openconfig-system:system -v 0 -target OC-YANG

**No response here**

^CE0910 05:42:22.302539 241 gnmi_cli.go:185] sendQueryAndDisplay(ctx, {Addrs:[127.0.0.1:8080] AddressChains:[] Target:OC-YANG Replica:0 UpdatesOnly:false Queries:[[openconfig-system:system]] Type:stream Timeout:30s NotificationHandler:<nil> ProtoHandler:<nil> Credentials:<nil> TLS:0xe08940 Extra:map[] SubReq:<nil> Streaming_type:ON_CHANGE Streaming_sample_int:0 Heartbeat_int:0 Suppress_redundant:false}, &{PollingInterval:30s StreamingDuration:0s Count:0 countExhausted:false Delimiter:/ Display:0x8692b0 DisplayPrefix: DisplayIndent: DisplayType:group DisplayPeer:false Timestamp: DisplaySize:false Latency:false ClientTypes:[gnmi]}):
rpc error: code = Canceled desc = context canceled
root@sonic:/#

telemetry.log:

Sep 10 05:03:23.875230 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874404 38 client_subscribe.go:97] Client 127.0.0.1:54940 recieved initial query subscribe:<prefix:<target:"OC-YANG" > subscription:<path:<element:"openconfig-system:system" elem:<name:"openconfig-system:system" > > mode:ON_CHANGE > >
Sep 10 05:03:23.875230 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874618 38 client_subscribe.go:155] Client 127.0.0.1:54940 running
Sep 10 05:03:23.875628 sonic INFO telemetry#supervisord: telemetry ON_CHANGE 0
Sep 10 05:03:23.875628 sonic INFO telemetry#supervisord: telemetry subscribe_mode: ON_CHANGE
Sep 10 05:03:23.875671 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874753 38 db.go:310] NewDB: Init indication not requested
Sep 10 05:03:23.875835 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874796 38 app_interface.go:116] getAppModule called for path =/openconfig-system:system
Sep 10 05:03:23.875967 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874815 38 app_interface.go:123] found the entry in the map for path =/openconfig-system:system
Sep 10 05:03:23.875967 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874832 38 app_interface.go:154] cast to appInterface worked&{<nil> [] <nil> <nil>}
Sep 10 05:03:23.876127 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.874964 38 db.go:310] NewDB: Init indication not requested
Sep 10 05:03:23.876127 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.875002 38 app_interface.go:116] getAppModule called for path =/openconfig-system:system
Sep 10 05:03:23.876127 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.875020 38 app_interface.go:123] found the entry in the map for path =/openconfig-system:system
Sep 10 05:03:23.876165 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.875046 38 app_interface.go:154] cast to appInterface worked&{<nil> [] <nil> <nil>}
Sep 10 05:03:23.876165 sonic INFO telemetry#supervisord: telemetry I0910 05:03:23.875068 38 translib.go:511] map=map[]

Sep 10 05:42:22.303323 sonic INFO telemetry#supervisord: telemetry I0910 05:42:22.302374 38 client_subscribe.go:198] Client 127.0.0.1:54940 received error: rpc error: code = Canceled desc = context canceled

Primary Analysis by DevTest (Level of debugging done / Devtest Observation ) :
---------------------------------------------------------------------------------------------------------

3.5.1.5.2 STREAM Subscriptions
Stream subscriptions are long-lived subscriptions which continue to transmit updates relating to the set of paths that are covered within the subscription indefinitely.

A STREAM subscription is created by sending a SubscribeRequest message with the subscribe field containing a SubscriptionList message with the type specified as STREAM. Each entry within the Subscription message is specified with one of the following modes:

On Change (ON_CHANGE) - when a subscription is defined to be "on change", data updates are only sent when the value of the data item changes.
For all ON_CHANGE subscriptions, the target MUST first generate updates for all paths that match the subscription path(s), and transmit them. Following this initial set of updates, updated values SHOULD only be transmitted when their value changes.
A heartbeat interval MAY be specified along with an "on change" subscription - in this case, the value of the data item(s) MUST be re-sent once per heartbeat interval regardless of whether the value has changed or not.

Reproducibility ( Ex:- 3 out of 3 attempts ) Please also update "Reproducible" field :
-------------------------------------------------------------------------------------------------------------

 3/3

**Comment by jeffyin-dell** [comment]
Not sure if this is expected behavior for gNMI, or if it's an issue with the "system" SUBSCRIBE support. Initially assigned to both @seiferteric and @arunsundark

**Comment by seiferteric** [comment]
Each App module has to implement onChange subscribe for any paths that it wants to support, in this case system app module is not implementing any onChange subscribe at all, so this is not expected to work.

**Comment by seiferteric** [comment]
> Not sure if this is expected behavior for gNMI, or if it's an issue with the "system" SUBSCRIBE support. Initially assigned to both @seiferteric and @arunsundark

@jeff-yin correct, it is up to the app module. System app module does not support onChange subscribe at all currently.

**Comment by jeffyin-dell** [comment]
@arunsundark is this a bug? Is /openconfig-system:system expected to change at all? If "system app module is not implementing any onChange subscribe at all" then we should close this since it's working-as-intended.

**Comment by jeffyin-dell** [comment]
I'm going to close this bug according to @seiferteric 's comments. system app module isn't supporting onChange subscribe.
